### ISSUE TITLE
Update README to point to v1.1 version

### ISSUE THREAD

**Issue by lintool** [castorini/mr.tydi#2]
Update docs to point to hgf datasets

The instructions need to change, I think?

```
(python36) iMac-Pro:mrtydi-v1.1-arabic jimmylin$ gunzip -c  dev.jsonl.gz | less
(python36) iMac-Pro:mrtydi-v1.1-arabic jimmylin$ pwd
/tuna1/collections/mr-tydi/mrtydi-v1.1-arabic
(python36) iMac-Pro:mrtydi-v1.1-arabic jimmylin$ gunzip -c  dev.jsonl.gz | head
{"query_id": "0", "query": "هل عدم القيام بجهد جسماني ممكن ان يسبب الأرق؟", "positive_passages": [{"docid": "151236#12", "title": "", "text": ""}]}
{"query_id": "9", "query": "من هي المغنية العربية التي قامت بأداء شارة مسلسل الرسوم المتحركة (حكايات عالمية) لأول مرة؟", "positive_passages": [{"docid": "401329#2", "title": "", "text": ""}]}
{"query_id": "29", "query": "ما هي منظمة الاوبك ؟", "positive_passages": [{"docid": "233622#0", "title": "", "text": ""}]}
{"query_id": "31", "query": "متى تأسست شركة الفودافون؟", "positive_passages": [{"docid": "316572#4", "title": "", "text": ""}]}
{"query_id": "32", "query": "متى عاش إبن الهيثم ؟", "positive_passages": [{"docid": "1803#0", "title": "", "text": ""}]}
{"query_id": "34", "query": "متى توفيت فاتن حمامة؟", "positive_passages": [{"docid": "48533#0", "title": "", "text": ""}]}
{"query_id": "35", "query": "متى عقدت الجمعية البرلمانية لمجلس أوروبا دورتها الأولى؟", "positive_passages": [{"docid": "2902421#1", "title": "", "text": ""}]}
{"query_id": "42", "query": "ما هو المدفع الجيني؟", "positive_passages": [{"docid": "4924278#0", "title": "", "text": ""}]}
{"query_id": "47", "query": "من اخترع لغة البايثون؟", "positive_passages": [{"docid": "12669#1", "title": "", "text": ""}]}
{"query_id": "57", "query": "هل تعد النعامة أكبر الطيورحجماً في العالم؟", "positive_passages": [{"docid": "1547903#8", "title": "", "text": ""}]}
```

The dataset is in json, so you need a simple script to convert into tsv queries and qrels to feed directly into Pyserini?

**Comment by crystina-z** [comment]
In Pyserini do we want to download from hgf or the one we uploaded (from the readme.md of this repo) tho? If it's the latter, maybe we just need to separate qrels from the other data?

**Comment by lintool** [comment]
Everything should be based off hgf?

So in the hgf repo, just add a simple Python script to convert the json into our standard query tsv and qrels?

What do you think?

**Comment by MahmoudWahdan** [comment]
Hello @lintool @crystina-z ,
Any updates regarding this issue?
Could you please point the inks for Pre-build sparse and dense indexes ?

Thanks.

**Comment by lintool** [comment]
hi @MahmoudWahdan for BM25 baselines, see: https://github.com/castorini/pyserini/pull/928

We're working on the mDPR baselines next.

**Comment by MahmoudWahdan** [comment]
Thanks @lintool for the great work. Could you please provide download links for V1.1 data and other available models/indexes files?

**Comment by crystina-z** [comment]
hi @MahmoudWahdan , the v1.1 data can be found on huggingface dataset -
for training set, qrels and topics: https://huggingface.co/datasets/castorini/mr-tydi
for corpus: https://huggingface.co/datasets/castorini/mr-tydi-corpus

**Comment by lintool** [comment]
@crystina-z We should still update the README, per title of issue...

**Comment by MahmoudWahdan** [comment]
@crystina-z Could you please update README with prebuilt indexes for version 1.1? and what are commands you used to index both Dense and Sparse indexes?
Thanks.

**Comment by crystina-z** [comment]
hi @MahmoudWahdan sorry for the long wait, we just updated the prebuilt [sparse](https://github.com/castorini/mr.tydi#2-pre-built-sparse-index-for-bm25) and [dense](https://github.com/castorini/mr.tydi#3-pre-built-dense-index-for-mdpr) index. and the index commands can be found via the link in Table [here](https://github.com/castorini/mr.tydi#baselines-and-evaluation).

**Comment by MahmoudWahdan** [comment]
Hi @crystina-z Thanks for the updates. I was able to prepare collection, index both Sparse and Dense passages, and reproduce almost the same results as in the paper for Arabic.
Thanks for your efforts.
I'd appreciate if you share more details about training mDPR from scratch.

**Comment by crystina-z** [comment]
Heyy @MahmoudWahdan that's nice to hear. 

The NQ ckpt we had is from another previous project, which I was not involved in. but I think the training is mostly based on the [DPR](https://github.com/facebookresearch/DPR) repo with the following command:
```
python -m torch.distributed.launch --nproc_per_node=1 \
train_dense_encoder.py \
  train=biencoder_nq \
  encoder=hf_mbert \
  train_datasets=[nq_train,nq_train_hn1] \
  dev_datasets=[nq_dev] \
  output_dir=baseline_mbert_retrieval_output
```
where the contents in `hf_mbert` is:
`conf/encoder/hf_mbert.yaml`
```
# @package _group_

# model type. One of [hf_bert, pytext_bert, fairseq_roberta]
encoder_model_type: hf_bert

# HuggingFace's config name for model initialization
pretrained_model_cfg: bert-base-multilingual-cased

# Some encoders need to be initialized from a file
pretrained_file:

# Extra linear layer on top of standard bert/roberta encoder
projection_dim: 0

# Max length of the encoder input sequence
sequence_length: 256

dropout: 0.1

# whether to fix (don't update) context encoder during training or not
fix_ctx_encoder: False

# if False, the model won't load pre-trained BERT weights
pretrained: True
```

**Comment by MahmoudWahdan** [comment]
Hi @crystina-z ,
Thank you very much! appreciated. Great efforts!
