### ISSUE TITLE
Dense index for my Arabic collection

### ISSUE THREAD

**Issue by Fatima-Haouari** [castorini/mr.tydi#5]
Could you please help on how can I dense index my own collection. Specifically I have the following questions:
I was following the command in this [link ](https://github.com/castorini/pyserini/blob/master/pyserini/resources/index-metadata/faiss.mrtydi-v1.1-arabic.20220207.5df364.README.md)but I have these specific questions:
1) If my collection is in json files as required for sparse indexing. Can I use it for dense indexing or different files format is needed.
2) Do we have to specify --fields 
3) I believe --delimiter "\n\n" is not valid for json files
4) I am getting this error regarding the model  **raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/models/mdpr-context-encoder**

**Comment by crystina-z** [comment]
Hi @Fatima-Haouari ! Thanks for your interest in our work. 

For 1-3, I guess [this](https://github.com/castorini/pyserini#dense-indexes) part of documentations from Pyserini might be helpful. There you can find information about the input file format, and how to use `--fields`. Regarding your questions - 
1. It might depend. The only format that dense indexing supports is the `{"id": ..., "contents": ...}`, where there can be multiple fields under the `contents`;
2. If you have multiple fields (e.g. title, text, URL, ..) then you would need to specify `--fields`
3. the `--delimiter` option is recently added, and is only supported from Pyserini 1.16.0. Could you check if your version matched? let us know if the issue still exists for versions after this.
4. My bad that I forgot to update the link. here is the one for passage encoder - [castorini/mdpr-passage-nq](https://huggingface.co/castorini/mdpr-passage-nq/tree/main)

**Comment by Fatima-Haouari** [comment]
Thanks a lot for your quick response.
My collection is in json format and data I want to encode is already in contents field as I already did the sparse indexing.
My pyserini version is 0.14.0 so I don't need delimiter right?
Could you please help with the model should I specify it as in below command:
 **python -m pyserini.encode input --corpus path-to-data output --embeddings path-to-index --to-faiss encoder --encoder castorini/mdpr-passage-nq --batch 128 --fp16**

**Comment by Fatima-Haouari** [comment]
I have another question please since the encoder model is a trained mBERT model as per the paper. Is there a limitation on the length of documents to index? does it work for long documents?
Is GPU a must or it can be done in a CPU?

**Comment by crystina-z** [comment]
> My collection is in json format and data I want to encode is already in contents field as I already did the sparse indexing.

Then I'm guessing it's fine, but just in case, do you have an example of the input?

> My pyserini version is 0.14.0 so I don't need delimiter right?

In pyserini 0.14.0 `delimiter` could not be controlled via command line and its value is always `\n`. If the fields in the `contents` are separated by `\n`, then yes you won't need delimiter, but otherwise you would need to upgrade to 0.16.0 and use it.

> Is there a limitation on the length of documents to index. Is GPU a must or it can be done in a CPU?

Yea I'm afraid the length is limited to 512, and for index a GPU is necessary. For retrieval it can be done on CPU.

**Comment by Fatima-Haouari** [comment]
Thanks for your help. I appreciate it.

**Comment by Fatima-Haouari** [comment]
Hi,
Regarding indexing I installed V 0.17.0. I followed the the pyserini installation guide [here ](https://github.com/castorini/pyserini/blob/master/docs/installation.md) and installed on a GPU however I am getting the following error:
 **RuntimeError: No HIP GPUs are available**  is there any specific installation requirements as I can see for example that faiss-cpu is installed not faiss-gpu is this fine?

Also for the command for the delimiter it should be **--delimeter --delimiter "\n\n"** ?

**Comment by crystina-z** [comment]
Hi @Fatima-Haouari For the faiss installation, I guess `conda list faiss` would should if it's `faiss-cpu` or `faiss-gpu` is installed. 

and yes, it should be `--delimeter --delimiter "\n\n"` (just one `--delimiter`)
