### ISSUE TITLE
Question about negative passages in Mr. TyDi

### ISSUE THREAD

**Issue by zhizhizhizhihan** [castorini/mr.tydi#6]
Hi, I'm curious about the negative passages in Mr. TyDi dataset. How do you annotate these negative passages (manually or automatically) for each query? Thank you!

**Comment by crystina-z** [comment]
Hi @zhizhizhizhihan ! Thanks for your interest in our work! 

I assume you are mentioning about the negative passages in hugging face dataset. Those are all non-positive passages in the top30 bm25 results. We did not manually label the negative examples.

**Comment by zhizhizhizhihan** [comment]
Thanks for your quick reply! Could you please kindly share the annotation script so we can use the same process to get bm25 hard negatives for other datasets?

**Comment by crystina-z** [comment]
Hi @zhizhizhizhihan , sure, the core code is basically [this](https://gist.github.com/crystina-z/233364db95baaf33ebdd2311c9cae037#file-sample_training_neg_prep-py-L19-L26) . hope it helps
