### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by xiyanghu** [castorini/mr.tydi#8]
It seems like this repo only provides evaluation scripts. Could you please kindly share the code/scripts for training on the EnglishQA dataset Natural Questions?

**Comment by crystina-z** [comment]
Hi @xiyanghu! thanks for your interest in our work! Sadly the code to train the checkpoint is part of another code base which's hard to exact from, but it should be able to reproduced using the Tevatron framework. The corresponding documentation is here - https://texttron.github.io/tevatron/training/#basic-training.
